export const FETCH_MOVIE_REQUEST = "FETCH_MOVIE_REQUEST"
export const FETCH_MOVIE_SUCCESS = "FETCH_MOVIE_SUCCESS"
export const FETCH_MOVIE_ERROR = "FETCH_MOVIE_ERROR"

export const MOVIE_CREATE = "MOVIE_CREATE"
export const MOVIE_UPDATE = "MOVIE_UPDATE"
export const MOVIE_DELETE = "MOVIE_DELETE"
export const MOVIE_SORT_BY = "MOVIE_SORT_BY"
export const MOVIE_DESCRIPTION = 'MOVIE_DESCRIPTION'
export const MOVIE_GENRE = 'MOVIE_GENRE'
export const MOVIE_ASC_DESC = 'MOVIE_ASC_DESC'
export const MOVIE_SEARCH_BY_TITLE = 'MOVIE_SEARCH_BY_TITLE'
